environment:
  nodejs_version: "7.6"

install:
  - ps: Install-Product node $env:nodejs_version

test_script:
  - npm install
  - npm run test
  - dir node_modules\.bin

# Make clone much faster
shallow_clone: true

# Disable Visual Studio build and deploy
build: off
deploy: off

# Cache node modules, and refresh if package.json changes
#cache:
#  - node_modules -> package.json